name: Run Python Script on Tag

on:
  push:
    tags:
      - '*'  # Trigger on all tags

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script with tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Running script with tag: $TAG_NAME"
          python schemas/isaric_schema.py "$TAG_NAME"

      - name: Commit and push changes
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add arc_$TAG_NAME_isaric_long_schema.json
            git commit -m "Add generated schema for tag $TAG_NAME" || echo "No changes to commit"
            git push
        env:
            TAG_NAME: ${GITHUB_REF#refs/tags/}
